### ISSUE TITLE
ImportError: DLL load failed while importing _pyllamacpp: The dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by Burgeon0110** [nomic-ai/pygpt4all#72] opened 2023-04-21 13:31 UTC
File "D:\gpt4all-ui\pyGpt4All\api.py", line 15, in <module>
    from pyGpt4All.backends import BACKENDS_LIST
  File "D:\gpt4all-ui\pyGpt4All\backends\__init__.py", line 1, in <module>
    from pyGpt4All.backends.llama_cpp import LLAMACPP
  File "D:\gpt4all-ui\pyGpt4All\backends\llama_cpp.py", line 12, in <module>
    from pyllamacpp.model import Model
  File "D:\gpt4all-ui\env\Lib\site-packages\pyllamacpp\model.py", line 21, in <module>
    import _pyllamacpp as pp
ImportError: DLL load failed while importing _pyllamacpp: The dynamic link library (DLL) initialization routine failed.

**Comment by abdeladim-s** [comment] 2023-04-23 21:59
Duplicate of #53

**Closed by abdeladim-s** 2023-04-23 21:59 UTC
