### ISSUE TITLE
6604 illegal hardware instruction

### ISSUE THREAD

**Issue by Lionardo** [nomic-ai/pygpt4all#78] opened 2023-04-25 07:51 UTC
I have the issue that I can't run the model inside my virtual env

my code:

```python

from pygpt4all.models.gpt4all_j import GPT4All_J


def new_text_callback(text):
    print(text, end="")


model = GPT4All_J('./models/ggml-gpt4all-j-v1.3-groovy.bin')
model.generate("Once upon a time, ", n_predict=55,
               new_text_callback=new_text_callback)

````

I have pipenv active and run the script provided in the readme like so

> pipenv run python3 gpt4all-j.py  

```
gptj_model_load: loading model from './models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
[1]    6604 illegal hardware instruction  pipenv run python3 gpt4all-j.py
```

Any idea as to how to go about this?

**Comment by Canahmetozguven** [comment] 2023-04-29 08:41
I'm using Mac m1 same

**Comment by abdeladim-s** [comment] 2023-05-02 20:18
@Lionardo, @Canahmetozguven 

I think it is duplicate of #57.
Please take a look at this [comment](https://github.com/nomic-ai/pygpt4all/issues/57#issuecomment-1519197837)

**Closed by abdeladim-s** 2023-05-02 20:18 UTC
